#!/usr/bin/env bash
set -euo pipefail

# One-time OpenAI CLI setup for macOS/Linux shells.
# - Stores OpenAI env vars in ~/.openai-env (chmod 600)
# - Ensures shell rc file sources ~/.openai-env
# - Optionally configures local HTTP/HTTPS proxy

DEFAULT_PROXY_URL="http://127.0.0.1:7890"
OPENAI_ENV_FILE="$HOME/.openai-env"
DEFAULT_OPENAI_BASE_URL="https://api.openai.com/v1"
DEFAULT_OPENAI_MODEL="gpt-4.1-mini"
DEFAULT_OPENAI_API_FORMAT="chat_completions"

is_valid_api_key() {
  local key="$1"
  [[ "$key" == sk-* && "${#key}" -ge 20 ]]
}

prompt_yes_no() {
  local prompt="$1"
  local default_choice="$2"
  local answer

  while true; do
    read -r -p "$prompt" answer
    answer="${answer:-$default_choice}"

    case "$answer" in
      y|Y|yes|YES|Yes)
        printf "y"
        return 0
        ;;
      n|N|no|NO|No)
        printf "n"
        return 0
        ;;
      *)
        printf "Please enter y or n.\n" >&2
        ;;
    esac
  done
}

prompt_for_api_key() {
  local api_key_input

  while true; do
    printf "Paste your new OpenAI API key and press Enter.\n" >&2
    printf "Enter q to cancel setup.\n" >&2
    read -r api_key_input

    if [[ "$api_key_input" == "q" || "$api_key_input" == "Q" ]]; then
      printf "Setup cancelled.\n" >&2
      exit 1
    fi

    if is_valid_api_key "$api_key_input"; then
      printf "%s" "$api_key_input"
      return 0
    fi

    printf "Invalid API key format. It should start with 'sk-'. Please paste the full key and try again.\n" >&2
  done
}

choose_model() {
  local choice

  while true; do
    printf "\nChoose a default model:\n"
    printf "  1) gpt-4.1-mini  - fast and low-cost, good default for agents\n"
    printf "  2) gpt-4.1       - stronger general reasoning\n"
    printf "  3) Custom model  - enter a model name manually\n"

    read -r -p "Model choice [1]: " choice
    choice="${choice:-1}"

    case "$choice" in
      1)
        openai_model="gpt-4.1-mini"
        return 0
        ;;
      2)
        openai_model="gpt-4.1"
        return 0
        ;;
      3)
        read -r -p "Enter model name: " custom_model
        custom_model="${custom_model:-$DEFAULT_OPENAI_MODEL}"
        openai_model="$custom_model"
        return 0
        ;;
      *)
        printf "Please enter 1, 2, or 3.\n" >&2
        ;;
    esac
  done
}

remove_proxy_block() {
  if grep -Fq "# OPENAI_PROXY_START" "$RC_FILE"; then
    awk '
      BEGIN { in_block=0 }
      /^# OPENAI_PROXY_START$/ { in_block=1; next }
      /^# OPENAI_PROXY_END$/ { in_block=0; next }
      { if (!in_block) print }
    ' "$RC_FILE" > "$RC_FILE.tmp"
    mv "$RC_FILE.tmp" "$RC_FILE"
  fi
}

detect_rc_file() {
  local shell_name
  shell_name="$(basename "${SHELL:-}")"

  case "$shell_name" in
    zsh)
      printf "%s/.zshrc" "$HOME"
      ;;
    bash)
      printf "%s/.bashrc" "$HOME"
      ;;
    *)
      if [[ -f "$HOME/.zshrc" ]]; then
        printf "%s/.zshrc" "$HOME"
      else
        printf "%s/.bashrc" "$HOME"
      fi
      ;;
  esac
}

RC_FILE="$(detect_rc_file)"

mkdir -p "$(dirname "$OPENAI_ENV_FILE")"
touch "$RC_FILE"

add_line_if_missing() {
  local line="$1"
  local file="$2"
  if ! grep -Fq "$line" "$file"; then
    printf "\n%s\n" "$line" >> "$file"
  fi
}

printf "OpenAI setup script\n"
printf "Using shell rc file: %s\n" "$RC_FILE"
printf "This script will guide you through setup and save the config automatically.\n"
printf "Tip: when asked for your API key, paste it normally and press Enter.\n"
printf "The default OpenAI API endpoint will be used automatically.\n"
printf "If you need an API key, open: https://platform.openai.com/api-keys\n"
printf "OpenAI quickstart docs: https://platform.openai.com/docs/quickstart\n"

# 1) Configure API key securely
if [[ -n "${OPENAI_API_KEY:-}" ]]; then
  printf "Detected OPENAI_API_KEY in current session.\n"
  use_current="$(prompt_yes_no "Use current key and save it to $OPENAI_ENV_FILE? [y/n, default y]: " "y")"
else
  use_current="n"
fi

if [[ "$use_current" == "y" ]]; then
  api_key="$OPENAI_API_KEY"
else
  printf "Current key will not be reused.\n"
  api_key="$(prompt_for_api_key)"
fi

openai_base_url="$DEFAULT_OPENAI_BASE_URL"
choose_model

cat > "$OPENAI_ENV_FILE" <<EOF
# Generated by setup_openai.sh
export OPENAI_API_KEY="$api_key"
export OPENAI_BASE_URL="$openai_base_url"
export OPENAI_MODEL="$openai_model"
export OPENAI_API_FORMAT="$DEFAULT_OPENAI_API_FORMAT"
EOF
chmod 600 "$OPENAI_ENV_FILE"

add_line_if_missing 'source "$HOME/.openai-env"' "$RC_FILE"

# 2) Optional proxy setup
set_proxy="$(prompt_yes_no "Configure HTTP/HTTPS proxy in $RC_FILE? [y/n, default n]: " "n")"
if [[ "$set_proxy" == "y" ]]; then
  read -r -p "Proxy URL [${DEFAULT_PROXY_URL}]: " proxy_url
  proxy_url="${proxy_url:-$DEFAULT_PROXY_URL}"

  if ! grep -Fq "# OPENAI_PROXY_START" "$RC_FILE"; then
    cat >> "$RC_FILE" <<EOF

# OPENAI_PROXY_START
export HTTP_PROXY="$proxy_url"
export HTTPS_PROXY="$proxy_url"
# OPENAI_PROXY_END
EOF
  else
    # Update existing block without duplicating
    awk -v proxy="$proxy_url" '
      BEGIN { in_block=0 }
      /^# OPENAI_PROXY_START$/ {
        print
        print "export HTTP_PROXY=\"" proxy "\""
        print "export HTTPS_PROXY=\"" proxy "\""
        in_block=1
        next
      }
      /^# OPENAI_PROXY_END$/ { in_block=0; print; next }
      { if (!in_block) print }
    ' "$RC_FILE" > "$RC_FILE.tmp"
    mv "$RC_FILE.tmp" "$RC_FILE"
  fi
else
  remove_proxy_block
fi

# 3) Load now for current shell
# shellcheck disable=SC1090
source "$OPENAI_ENV_FILE"

if [[ -n "${HTTP_PROXY:-}" || -n "${HTTPS_PROXY:-}" ]]; then
  printf "Proxy in current shell: HTTP_PROXY=%s HTTPS_PROXY=%s\n" "${HTTP_PROXY:-<unset>}" "${HTTPS_PROXY:-<unset>}"
fi

printf "\nSetup complete.\n"
printf "Next steps:\n"
printf "1) Reload your current shell so the new config takes effect:\n"
printf "   source %s\n" "$RC_FILE"
printf "2) Verify env loaded:\n"
printf "   [ -n \"\$OPENAI_API_KEY\" ] && echo ok\n"
printf "3) Start Mochi from VS Code with the 'Run Local Agent Extension' launch config.\n"
printf "4) Official docs:\n"
printf "   API keys: https://platform.openai.com/api-keys\n"
printf "   Quickstart: https://platform.openai.com/docs/quickstart\n"
printf "\nNote: this script cannot modify the parent terminal session directly,\n"
printf "so please run the 'source' command above once after setup.\n"
